### ISSUE TITLE
(RF)RFC: resource-determined triggerability of versions

### ISSUE THREAD

**Issue by vito** [concourse/rfcs#11]
The `git` resource has config like `paths` and `ignore_paths`, plus support for `ci skip`.

Right now this functionality works by not returning those versions. But usually that's not *really* what the user wants: they just don't want to auto-trigger on those commits. Most of the time they would still prefer to run with the latest if a build triggers for some other reason.

Could we just have the versions say `trigger: true/false` and have the scheduler know not to queue builds if the only new versions are all `trigger: false`?

**Comment by jchesterpivotal** [comment]
Filtering is a pretty common concern in a lot of resources, done in lots of different ways. I see a lot of regexps.

I think an important distinction is whether the filtering is for logical purposes or performance purposes. If it's for logical purposes, it's useful to keep a record that the version was recognised but would not trigger. `ci skip` is such an example. On the other hand, performance filtering should be pushed as far upstream as possible -- eg. a resource that subscribes to a remote webhook might prefer to pass filtering instructions to the upstream service instead.

Aside: maybe we could pinch something from [Open Policy Agent's Rego language](https://github.com/open-policy-agent/opa/blob/master/design/REGO_V2_PROPOSAL.md) for filtering?

**Comment by vito** [comment]
@jchesterpivotal Agreed - I think it's important to note that this is specifically for triggerability, *not* general filtering. Right now they're conflated because filtering is the only way to do this, but has the downsides mentioned above - the intent is to prevent triggering, but there's no reason to not let the versions be recorded.

Any more advanced filtering is still best left up to the resource to implement IMO. Spaces will also provide at least one vector by which users can choose to filter the versions that they want.
