### ISSUE TITLE
(RF)RFCs: next iteration of credential manager support

### ISSUE THREAD

**Issue by vito** [concourse/rfcs#5]
I'm opening this issue as a call to action for anyone familiar with any of the existing credential managers:

* Vault
* CredHub
* AWS SSM
* AWS SecretsManager
* Kubernetes

I think it makes sense to discuss each of these as separate RFCs as I don't expect anyone is intimately familiar with *all* of them. If you're willing to throw your hat in the ring, go ahead and submit a PR with your own RFC! If there's only one specific aspect you feel that you're knowledgeable enough to propose, go ahead and start there. We can work together towards a consistent solution over time. We just need to get the ball rolling first.

# Feedback

We've already received a fair amount of feedback for some credential managers. Mostly Vault, as that's the first one we shipped and seems to have had the most traction (or at least the most opinionated people giving feedback!)

## Using arbitrary paths

* https://github.com/concourse/concourse/issues/1391
* https://github.com/concourse/concourse/issues/1814
* https://github.com/concourse/atc/pull/273

CredHub/Vault (probably all) users want to be able to use credentials at arbitrary paths, not just the Concourse-enforced schema (`/concourse/TEAM/PIPELINE/CRED`). This would allow secrets to be reused rather than copied.

Being able to use arbitrary paths would also allow Vault users to use different secret backends for each credential. The current implementation forces users to use the "generic" backend, if they're using recent releases of Vault.

This would be problematic at the moment because credential managers are globally configured, with a single auth scheme (not per-team). So permitting arbitrary path usage would result in team A being able to read team B's credentials, which is Very Bad. Which leads us to...

## Per-team credential manager configuration

* https://github.com/concourse/concourse/issues/1814

This would allow teams to use their own private credential managers, and allow one team to use CredHub while another uses Vault. This would allow teams to have different tokens with e.g. Vault, and delegate credential access to Vault's access controls rather than enforcing the path scheme.

We should be careful to encrypt the credential manager config now that it's sitting in the database.

## Credential caching

* https://github.com/concourse/atc/pull/236
* https://github.com/concourse/atc/pull/238

Right now Concourse resolves credentials every time they're used, which can hit Vault and CredHub pretty hard. @rfliam submitted a PR to cache Vault credentials, but in principle this is something we may be able to do generically. (Vault makes it easier to do correctly by having lease durations, but other backends could have some static configuration to determine this at least.)

## Other feedback?

I may be missing some stuff here, so feel free to drop in more feedback in the comments. Let's use the text of this first issue as the "source of truth" though - I'll edit it as more feedback comes in.

**Comment by sammy** [comment]
Hi there,

I d like to drop a suggestion for Vault.
The idea is that a task should be able to load all available parameters under its pipeline's Vault path and Teams root path, either by default or by a flag, or from an external file.
So our params section for a task could look like:

Assuming team name main and pipeline deploy.to.staging the snippet below would load by default values stored in vault under /councourse/main/ and /concourse/main/deploy.to.staging

params:
  load_all: true

With the snippet below we could maintain a params file in the code repo, and reuse the specific task for multiple repos
params:
  from_file: path/to/params/file

This way we can make tasks generic enough to be easily reusable.

I also described it here: https://discuss.concourse-ci.org/t/load-all-parameters-that-are-available-in-vault/310

Thks

**Comment by goldstar611** [comment]
I think secrets management engine errors should be prioritized and promoted to admin users in some fashion on the web interface.

For instance, I logged into Concourse CI (v4.2.1) and inspected my failing pipeline only to see an error related to Vault "missing client token". Things go wrong in a dev environment all the time, so first step is to just restart everything. But destroying/setting the pipeline, restarting vault, restarting concourse-web and concourse-workers did do anything for me because the actual error got buried in the syslog:
```
"Nov  1 13:48:53 concourse-testing concourse[3260]: {"timestamp":"1541098133.032745123","source":
"atc","message":"atc.credential-manager.login.failed","log_level":2,"data":{"error":"Error ma
king API request.\n\nURL: PUT https://127.0.0.1:8200/v1/auth/cert/login\nCode: 500. Errors:\n
\n* failed to verify client's certificate: x509: certificate has expired or is not yet valid"
,"name":"vault","session":"7.19"}}"
```
It would have been great to know up front that an expired Vault cert was the root issue to the "missing client token" issue.

**Comment by vito** [comment]
Per https://github.com/concourse/concourse/issues/3002 it may be time to reconsider how we support IAM roles from resources. Direct access is proving to be difficult to design around and goes against a few anti-patterns (worker state, multi-source-of-truth).

**Comment by vito** [comment]
As a follow-up to https://github.com/concourse/rfcs/issues/5#issuecomment-452365440 I've opened https://github.com/concourse/concourse/issues/3023 which proposes supporting IAM roles via the credential management interface.

This raises a couple concerns:

* Right now the ATC can only be configured with a single credential manager, and it would be kind of a waste to only be able to use IAM roles. This seems like something that may be in addition to some other credential manager.
* This implies configuring the ATC's EC2 instance with IAM roles, so we would need to be careful about which teams should be able to access it, if we ever do some sort of self-service per-team credential manager configuration. For example, if IAM roles are to be supported in a multi-tenant environment, it feels weird for teams to be able to configure it themselves. It feels more like an operator concern, and the operator should decide which teams have access to which roles. Maybe some credential managers are operator-configured and some are user-configured? Maybe it's all operator-configured and mapped to teams explicitly? Maybe this should all be dynamic (not static config/flags) and administered by some sort of admin role?

**Comment by elgohr** [comment]
At my point of view there are two ways:
* Giving teams a way to configure a credential manager themselves.
This would put more work to the teams, as they would need to set the credential manager up and keep it running (OPs).
Nevertheless teams could do whatever they want in the instance.
* Keeping the "generic" manager and configuring it via a fassade in which the ATC would need to care for consistency with IAM roles
This means that secrets are kept in a single spot, which probably makes it less secure.
The good part would be, that teams wouldn't have to care/learn another product

**Comment by aegershman** [comment]
It's an RFC, so I'm just putting ideas out there no matter how little fleshed out they are 😉 -- Giving teams access to configure their own credential manager would definitely be interesting. I wonder if going down that path could open up the possibility for teams to use something like a [Spring Cloud Config server](https://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#_encryption_and_decryption) which would enable teams to store their secrets encrypted in git. Granted they'd still need to store the private-key used to encrypt those values in the first place, but regardless, that'd be an interesting path to take.

**Comment by eamonryan** [comment]
I would like to see reuse of secrets be possible _across_ teams if desired/configured.

To give a specific example, currently there are patterns that have people using a separate Concourse team per PCF installation (for pipeline tidiness/accident prevention). Yet there are values that are common to multiple installations that would benefit from reading from a single source of truth.

So either having a common configurable arbitrary path that all teams can access e.g. /concourse/common or, preferably, the ability to define which teams may access which shared paths e.g. teamA and teamB may both access /arbitrary/shared/path but no others, would be fantastic.

**Comment by vito** [comment]
Small note: enforcing configurable timeouts for credential manager interactions may be desireable in the core.

**Comment by hprotzek** [comment]
> I would like to see reuse of secrets be possible _across_ teams if desired/configured.
> 
> To give a specific example, currently there are patterns that have people using a separate Concourse team per PCF installation (for pipeline tidiness/accident prevention). Yet there are values that are common to multiple installations that would benefit from reading from a single source of truth.
> 
> So either having a common configurable arbitrary path that all teams can access e.g. /concourse/common or, preferably, the ability to define which teams may access which shared paths e.g. teamA and teamB may both access /arbitrary/shared/path but no others, would be fantastic.

We are facing the same problem, many secrets are shared between all teams and had to be copied into the specific team path. We tried to solve this with this quite simple solution of an configurable shared lookup path inn vault:  https://github.com/concourse/concourse/pull/3221

**Comment by vito** [comment]
Thanks so much to everyone who has helped provide context for this so far. I've started on a proper RFC and would really appreciate any input y'all would have:

https://github.com/concourse/rfcs/pull/21

As this RFRFC has now resulted in an RFC I'm going to close this issue. :slightly_smiling_face:
